
import * as imageUris from './image-uris';
import { Gallery } from './gallery';

export enum GALLERY_ENUM {
  THE_DRAG = 'THE_DRAG',
  NEXT_FALL = 'NEXT_FALL',
  AGAMEMNON = 'AGAMEMNON',
  TRIBES = 'TRIBES',
  FAT_PIG = 'FAT_PIG',
  UVU = 'UVU',
  SUNDANCE = 'SUNDANCE',
  RENAISSANCE_NOW = 'RENAISSANCE_NOW',
  BYU = 'BYU',
  RENAISSANCE_FAIRE = 'RENAISSANCE_FAIRE',
  CABARET = 'CABARET',
  ART = 'ART',
  LARAMIE = 'LARAMIE',
  MRBURNS = 'MRBURNS',
  URINETOWN = 'URINETOWN',
  TAMINGOFTHESHREW = 'TAMINGOFTHESHREW',
}

export const GALLERIES: GALLERY_ENUM[] = [
  GALLERY_ENUM.THE_DRAG,
  GALLERY_ENUM.NEXT_FALL,
  GALLERY_ENUM.AGAMEMNON,
  GALLERY_ENUM.TRIBES,
  GALLERY_ENUM.FAT_PIG,
  GALLERY_ENUM.UVU,
  GALLERY_ENUM.SUNDANCE,
  GALLERY_ENUM.RENAISSANCE_NOW,
  GALLERY_ENUM.BYU,
  GALLERY_ENUM.RENAISSANCE_FAIRE,
  GALLERY_ENUM.CABARET,
  GALLERY_ENUM.ART,
  GALLERY_ENUM.LARAMIE,
  GALLERY_ENUM.MRBURNS,
  GALLERY_ENUM.URINETOWN,
  GALLERY_ENUM.TAMINGOFTHESHREW,
];

export const SCENIC_GALLERY_KEYS: GALLERY_ENUM[] = [
  GALLERY_ENUM.URINETOWN,
  GALLERY_ENUM.TAMINGOFTHESHREW,
  GALLERY_ENUM.MRBURNS,
  GALLERY_ENUM.LARAMIE,
  GALLERY_ENUM.THE_DRAG,
  GALLERY_ENUM.NEXT_FALL,
  GALLERY_ENUM.AGAMEMNON,
  GALLERY_ENUM.TRIBES,
  GALLERY_ENUM.FAT_PIG,
  GALLERY_ENUM.UVU,
  GALLERY_ENUM.SUNDANCE,
  GALLERY_ENUM.RENAISSANCE_NOW,
  GALLERY_ENUM.BYU,
  GALLERY_ENUM.CABARET,
  GALLERY_ENUM.RENAISSANCE_FAIRE,
];
